import React from 'react';
import type { ClinicalCase } from '../../types';
import { Sparkles, HeartPulse, ShieldAlert, Activity } from 'lucide-react';
import { useCase } from '../../hooks/useCase';
import { api } from '../../services/api';

interface ClinicalSummaryProps {
  currentCase: ClinicalCase;
}

export const ClinicalSummary: React.FC<ClinicalSummaryProps> = ({ currentCase }) => {
  const { refreshCase } = useCase();
  const { originalTranscript, aiClinicalSummary, aiSymptoms, aiConfidence, aiSeverity, patient } = currentCase;

  const handleUpdateStatus = async (newStatus: string) => {
    try {
      await api.updateCaseStatus(currentCase.id, newStatus);
      await refreshCase(currentCase.id);
    } catch (e) {
      console.error('Failed to update case status:', e);
    }
  };

  return (
    <div className="w-full bg-white rounded-xl border border-brand-teal/15 p-6 shadow-sm space-y-5 bg-plus-grid">
      {/* Clinician warning alert at the top */}
      <div className="bg-clinical-urgentLight border border-clinical-urgent/20 p-3.5 rounded-xl flex items-start gap-2.5">
        <ShieldAlert className="w-4 h-4 text-clinical-urgent shrink-0 mt-0.5" />
        <div className="text-xs">
          <span className="font-bold text-clinical-urgent block uppercase tracking-wider text-[10px]">
            Clinician Verification Required
          </span>
          <p className="text-brand-forest/90 mt-0.5 leading-relaxed">
            The transcript and summary below are generated by RuralCare ASR & Clinical NLP engines. Cross-verify clinical findings before signing prescriptions.
          </p>
        </div>
      </div>

      {/* Grid containing Voice transcript & AI summary */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* Left pane: Original Speech Transcript */}
        <div className="bg-brand-gray/40 border border-brand-teal/5 p-4 rounded-xl space-y-2">
          <span className="block text-[10px] font-bold text-brand-earth uppercase tracking-wider">
            Original Patient Speech Transcript
          </span>
          <blockquote className="text-xs font-medium text-brand-forest italic leading-relaxed relative pl-4 border-l-2 border-brand-teal/40">
            "{originalTranscript}"
          </blockquote>
          <div className="pt-2 text-[10px] text-brand-earth flex justify-between items-center">
            <span>Detected Language: <span className="font-semibold text-brand-forest">{currentCase.language}</span></span>
            <span>Severity: <span className="font-semibold text-clinical-emergency">{aiSeverity}</span></span>
          </div>
        </div>

        {/* Right pane: AI Clinical Summary */}
        <div className="bg-brand-teal/[0.02] border border-brand-teal/10 p-4 rounded-xl space-y-2 relative">
          {/* AI Tag */}
          <div className="absolute right-3 top-3 flex items-center gap-1 text-xs text-brand-teal bg-brand-teal/5 border border-brand-teal/10 px-2 py-0.5 rounded-lg">
            <Sparkles className="w-3 h-3 animate-pulse" />
            <span className="font-semibold uppercase tracking-wider text-[8px]">AI-Generated</span>
          </div>

          <span className="block text-[10px] font-bold text-brand-earth uppercase tracking-wider">
            AI Clinical Abstract Summary
          </span>
          <p className="text-xs text-brand-forest leading-relaxed font-semibold pr-16">
            {aiClinicalSummary}
          </p>

          <div className="pt-3 text-[10px] text-brand-earth flex items-center justify-between border-t border-brand-teal/5">
            <div className="flex items-center gap-1">
              <Activity className="w-3.5 h-3.5 text-brand-teal" />
              <span>Pipeline Confidence: <span className="font-bold text-brand-teal">{aiConfidence}%</span></span>
            </div>
            <span className="text-[8px] bg-brand-teal/10 text-brand-teal px-1.5 py-0.5 rounded border border-brand-teal/10 font-bold uppercase tracking-wider">
              NLP Class Verified
            </span>
          </div>
        </div>
      </div>

      {/* Extracted Symptoms */}
      <div className="space-y-2">
        <span className="block text-[10px] font-bold text-brand-earth uppercase tracking-wider">
          Extracted Clinical Markers & Symptoms
        </span>
        <div className="flex flex-wrap gap-2">
          {aiSymptoms.map((symptom, idx) => (
            <span
              key={idx}
              className="text-xs bg-brand-gray border border-brand-teal/10 px-2.5 py-1 rounded-lg text-brand-forest font-semibold flex items-center gap-1.5 shadow-sm"
            >
              <HeartPulse className="w-3 h-3 text-clinical-emergency" />
              {symptom}
            </span>
          ))}
        </div>
      </div>

      {/* Quick Demographic & Allergy Reference */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 border-t border-brand-teal/5 pt-4 text-xs">
        <div>
          <span className="block text-[10px] uppercase font-bold text-brand-earth/80">Allergy Alert</span>
          <span className="font-bold text-clinical-emergency bg-clinical-emergencyLight border border-clinical-emergency/20 px-2 py-0.5 rounded mt-0.5 inline-block text-[10px]">
            {patient.allergies}
          </span>
        </div>
        <div>
          <span className="block text-[10px] uppercase font-bold text-brand-earth/80">Chronic History</span>
          <span className="font-medium text-brand-forest block mt-0.5 leading-snug">{patient.medicalHistory}</span>
        </div>
        <div>
          <span className="block text-[10px] uppercase font-bold text-brand-earth/80">Active Medications</span>
          <span className="font-semibold text-brand-teal block mt-0.5 leading-snug">{patient.currentMedications}</span>
        </div>
      </div>

      {/* 📞 Phone/IVR Consultation details & Location */}
      {(currentCase.channel === 'phone_demo' || currentCase.channel === 'ivr_demo' || currentCase.locationText) && (
        <div className="bg-brand-gray/50 border border-brand-teal/10 p-4 rounded-xl space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold text-brand-earth uppercase tracking-wider flex items-center gap-1">
              📞 {currentCase.channel === 'ivr_demo' ? 'IVR Consultation Details' : 'Phone Consultation Details'}
            </span>
            <span className="text-[9px] bg-brand-teal text-white font-mono px-2 py-0.5 rounded-full font-bold">
              Channel: {currentCase.channel === 'ivr_demo' ? 'IVR Consultation (Demo)' : 'Phone Consultation (Demo)'}
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
            <div>
              <span className="block text-[10px] uppercase font-bold text-brand-earth/80">Caller Patient Phone</span>
              <span className="font-mono text-brand-forest font-bold block mt-0.5">{currentCase.callerPhone || patient.phone}</span>
            </div>
            <div>
              <span className="block text-[10px] uppercase font-bold text-brand-earth/80">Collected Location (Captured First)</span>
              <span className="font-semibold text-brand-forest block mt-0.5">{currentCase.locationText || patient.address}</span>
            </div>
            <div>
              <span className="block text-[10px] uppercase font-bold text-brand-earth/80">Selected Language</span>
              <span className="font-bold text-brand-teal block mt-0.5">
                {currentCase.languageCode === 'ta' ? '🇮🇳 Tamil' : currentCase.languageCode === 'en' ? '🇬🇧 English' : 'Not Specified'}
              </span>
            </div>
          </div>

          {/* IVR-ONLY: Ambulance / Field Worker actions (only for IVR channel + effective emergency) */}
          {currentCase.channel === 'ivr_demo' && currentCase.triagePriority === 'Emergency' && (
            <div className="border-t border-brand-teal/10 pt-3 mt-2">
              <span className="text-red-500 font-bold uppercase tracking-wider text-[10px] flex items-center gap-1.5 mb-2 animate-pulse">
                🚨 POTENTIAL EMERGENCY - Location and Phone captured above
              </span>
              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => alert(`[PROTOTYPE] Requesting ambulance dispatch to location: "${currentCase.locationText || patient.address}". (Emergency response integration — prototype)`)}
                  className="bg-red-500 hover:bg-red-600 text-white font-bold text-[10px] px-3.5 py-2 rounded-lg uppercase tracking-wider transition duration-150"
                >
                  Request Ambulance
                </button>
                <button
                  onClick={() => alert(`[PROTOTYPE] Alerting local community health worker to contact phone: ${currentCase.callerPhone || patient.phone}. (Emergency response integration — prototype)`)}
                  className="bg-brand-forest hover:bg-brand-forestLight text-brand-cream font-bold text-[10px] px-3.5 py-2 rounded-lg uppercase tracking-wider transition duration-150"
                >
                  Contact Health Worker
                </button>
                <button
                  onClick={() => alert(`[PROTOTYPE] Map Location Coordinates: Latitude: null, Longitude: null. Text Address: "${currentCase.locationText || patient.address}". (Emergency response integration — prototype)`)}
                  className="bg-brand-gray border border-brand-teal/15 hover:bg-brand-teal/15 text-brand-forest font-bold text-[10px] px-3.5 py-2 rounded-lg uppercase tracking-wider transition duration-150"
                >
                  View Location
                </button>
              </div>
              <span className="block text-[9px] text-brand-earth mt-1.5 italic">
                Emergency response integration — prototype. No real carrier services are triggered.
              </span>
            </div>
          )}
        </div>
      )}

      {/* ============================================================ */}
      {/* EFFECTIVE TRIAGE EMERGENCY ALERT — WORKS FOR ALL CHANNELS    */}
      {/* ============================================================ */}
      {(() => {
        const aiTriage = currentCase.aiTriageRecommend;
        const doctorTriage = currentCase.triagePriority;
        // Doctor triage is always set (defaults to AI value), so we check if doctor has actively changed it
        const doctorHasReviewed = doctorTriage !== aiTriage;
        const effectiveTriage = doctorTriage; // triagePriority IS the doctor's current/working triage

        // ---- TRIAGE STATUS DISPLAY (always show when AI or doctor flagged emergency) ----
        const showTriageDisplay = aiTriage === 'Emergency' || doctorTriage === 'Emergency';
        if (!showTriageDisplay) return null;

        // Determine which state we are in
        const isIvr = currentCase.channel === 'ivr_demo';

        return (
          <div className="space-y-4">
            {/* Triage Comparison Panel — always show both values */}
            <div className="bg-white border border-brand-teal/15 p-4 rounded-xl shadow-sm space-y-3">
              <span className="block text-[10px] font-bold text-brand-earth uppercase tracking-wider">
                Triage Assessment Overview
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                <div className="bg-brand-gray/40 border border-brand-teal/5 p-3 rounded-lg">
                  <span className="block text-[10px] uppercase font-bold text-brand-earth/80 mb-1">AI Preliminary Triage</span>
                  <span className={`font-black text-sm uppercase ${
                    aiTriage === 'Emergency' ? 'text-clinical-emergency' :
                    aiTriage === 'Urgent' ? 'text-clinical-urgent' : 'text-clinical-routine'
                  }`}>
                    {aiTriage === 'Emergency' ? '🚨' : aiTriage === 'Urgent' ? '🟡' : '🟢'} {aiTriage}
                  </span>
                </div>
                <div className="bg-brand-gray/40 border border-brand-teal/5 p-3 rounded-lg">
                  <span className="block text-[10px] uppercase font-bold text-brand-earth/80 mb-1">Doctor Triage</span>
                  <span className={`font-black text-sm uppercase ${
                    doctorTriage === 'Emergency' ? 'text-clinical-emergency' :
                    doctorTriage === 'Urgent' ? 'text-clinical-urgent' : 'text-clinical-routine'
                  }`}>
                    {doctorTriage === 'Emergency' ? '🚨' : doctorTriage === 'Urgent' ? '🟡' : '🟢'} {doctorTriage}
                  </span>
                </div>
                <div className={`p-3 rounded-lg border ${
                  effectiveTriage === 'Emergency'
                    ? 'bg-clinical-emergencyLight border-clinical-emergency/30'
                    : effectiveTriage === 'Urgent'
                    ? 'bg-clinical-urgentLight border-clinical-urgent/30'
                    : 'bg-clinical-routineLight border-clinical-routine/30'
                }`}>
                  <span className="block text-[10px] uppercase font-bold text-brand-earth/80 mb-1">Effective Triage</span>
                  <span className={`font-black text-sm uppercase ${
                    effectiveTriage === 'Emergency' ? 'text-clinical-emergency' :
                    effectiveTriage === 'Urgent' ? 'text-clinical-urgent' : 'text-clinical-routine'
                  }`}>
                    {effectiveTriage === 'Emergency' ? '🚨' : effectiveTriage === 'Urgent' ? '🟡' : '🟢'} {effectiveTriage}
                  </span>
                </div>
              </div>
            </div>

            {/* STATE 1: AI flagged EMERGENCY but doctor hasn't changed it yet → AI Warning */}
            {aiTriage === 'Emergency' && !doctorHasReviewed && (
              <div className="bg-red-50 border border-red-200/50 p-4 rounded-xl flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
                <div>
                  <span className="text-red-600 font-bold uppercase tracking-wider text-[10px] block animate-pulse">
                    ⚠️ AI FLAGGED POTENTIAL EMERGENCY
                  </span>
                  <span className="text-xs text-brand-forest font-bold block mt-0.5">
                    AI preliminary triage indicates a potential emergency. Clinician verification required.
                  </span>
                </div>
                <span className="text-[9px] bg-red-100 text-red-600 border border-red-200 px-2 py-1 rounded font-bold uppercase tracking-wider whitespace-nowrap">
                  Awaiting Doctor Review
                </span>
              </div>
            )}

            {/* STATE 2/4/5: effectiveTriage IS Emergency (doctor confirmed or doctor upgraded) → EMERGENCY CONFIRMED + Actions */}
            {effectiveTriage === 'Emergency' && doctorHasReviewed && !isIvr && (
              <div className="bg-red-50/50 border border-red-200/60 p-4 rounded-2xl space-y-4">
                <div>
                  <span className="text-red-600 font-black uppercase tracking-wider text-xs flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-red-500 animate-ping"></span>
                    🚨 EMERGENCY CONFIRMED
                  </span>
                  <p className="text-xs text-brand-forest font-medium mt-1">
                    {aiTriage !== 'Emergency'
                      ? 'Doctor has upgraded this case to EMERGENCY. Patient requires immediate attention.'
                      : 'Doctor has confirmed the AI emergency classification. Patient requires immediate attention.'}
                  </p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
                  <button
                    onClick={() => handleUpdateStatus('DOCTOR_REQUESTED')}
                    disabled={(currentCase.status as string) === 'DOCTOR_REQUESTED'}
                    className={`font-black text-[10px] px-3.5 py-2.5 rounded-xl uppercase tracking-wider transition duration-150 text-center border ${
                      (currentCase.status as string) === 'DOCTOR_REQUESTED'
                        ? 'bg-brand-gray border-brand-teal/10 text-brand-forest/40 cursor-not-allowed'
                        : 'bg-white border-brand-teal/20 hover:bg-brand-teal/5 text-brand-forest'
                    }`}
                  >
                    👨‍⚕️ Request Immediate Doctor
                  </button>
                  <button
                    onClick={() => handleUpdateStatus('STAFF_ALERTED')}
                    disabled={(currentCase.status as string) === 'STAFF_ALERTED'}
                    className={`font-black text-[10px] px-3.5 py-2.5 rounded-xl uppercase tracking-wider transition duration-150 text-center border ${
                      (currentCase.status as string) === 'STAFF_ALERTED'
                        ? 'bg-brand-gray border-brand-teal/10 text-brand-forest/40 cursor-not-allowed'
                        : 'bg-white border-brand-teal/20 hover:bg-brand-teal/5 text-brand-forest'
                    }`}
                  >
                    🧑‍⚕️ Alert Healthcare Staff
                  </button>
                  <button
                    onClick={() => handleUpdateStatus('HIGH_PRIORITY')}
                    disabled={(currentCase.status as string) === 'HIGH_PRIORITY'}
                    className={`font-black text-[10px] px-3.5 py-2.5 rounded-xl uppercase tracking-wider transition duration-150 text-center border ${
                      (currentCase.status as string) === 'HIGH_PRIORITY'
                        ? 'bg-red-500 border-red-500 text-white cursor-not-allowed'
                        : 'bg-white border-brand-teal/20 hover:bg-brand-teal/5 text-brand-forest'
                    }`}
                  >
                    🚨 Prioritize Patient
                  </button>
                </div>

                {/* Status feedback messages */}
                {(currentCase.status as string) === 'DOCTOR_REQUESTED' && (
                  <div className="bg-brand-teal/10 border border-brand-teal/20 p-3 rounded-xl">
                    <strong className="block text-[10px] font-bold text-brand-teal uppercase">👨‍⚕️ DOCTOR REQUESTED</strong>
                    <p className="text-[11px] font-semibold text-brand-forest mt-0.5">
                      "An available doctor has been requested to review this emergency case."
                    </p>
                  </div>
                )}
                {(currentCase.status as string) === 'STAFF_ALERTED' && (
                  <div className="bg-brand-forest/10 border border-brand-forest/20 p-3 rounded-xl">
                    <strong className="block text-[10px] font-bold text-brand-forest uppercase">🧑‍⚕️ HEALTHCARE STAFF ALERTED</strong>
                    <p className="text-[11px] font-semibold text-brand-forest mt-0.5">
                      "Healthcare staff have been notified about this high-priority patient."
                    </p>
                  </div>
                )}
                {(currentCase.status as string) === 'HIGH_PRIORITY' && (
                  <div className="bg-red-500/10 border border-red-500/20 p-3 rounded-xl">
                    <strong className="block text-[10px] font-bold text-red-500 uppercase">🚨 PATIENT PRIORITIZED</strong>
                    <p className="text-[11px] font-semibold text-brand-forest mt-0.5">
                      "Case moved to the high-priority emergency queue."
                    </p>
                  </div>
                )}
              </div>
            )}

            {/* STATE 3/6: AI flagged EMERGENCY but doctor overrode to non-emergency → Clinician Override */}
            {aiTriage === 'Emergency' && doctorHasReviewed && effectiveTriage !== 'Emergency' && (
              <div className="bg-green-50 border border-green-300/60 p-4 rounded-xl space-y-2">
                <div className="flex items-center gap-2">
                  <span className="font-black text-green-800 text-xs uppercase tracking-wider">✓ CLINICIAN OVERRIDE</span>
                </div>
                <p className="text-xs text-brand-forest leading-relaxed">
                  Doctor reviewed the AI preliminary emergency flag and classified this case as <strong className="uppercase">{effectiveTriage}</strong>.
                  The AI emergency classification has been overridden.
                </p>
              </div>
            )}
          </div>
        );
      })()}
    </div>
  );
};

export default ClinicalSummary;
